/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author hantr
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {

        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        trang_thai_mang = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cau_hinh_may_tinh = new javax.swing.JCheckBox();
        cau_hinh_may_tinh_fn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ngay_gio = new javax.swing.JCheckBox();
        ngay_gio_fn = new javax.swing.JTextField();
        cong_duoc_mo = new javax.swing.JCheckBox();
        trang_thai_mang_fn = new javax.swing.JTextField();
        ket_noi_duoc_thiet_lap = new javax.swing.JCheckBox();
        cong_duoc_mo_fn = new javax.swing.JTextField();
        ket_noi_thiet_lap = new javax.swing.JTextField();
        bang_dinh_tuyen = new javax.swing.JCheckBox();
        bang_dinh_tuyen_fn = new javax.swing.JTextField();
        du_lieu_qua_cong = new javax.swing.JCheckBox();
        du_lieu_qua_cong_fn = new javax.swing.JTextField();
        cac_tien_trinh = new javax.swing.JCheckBox();
        tien_trinh = new javax.swing.JTextField();
        nguoi_dung_dang_nhap = new javax.swing.JCheckBox();
        nguoi_dung_dang_nhap_fn = new javax.swing.JTextField();
        cau_hinh_mang = new javax.swing.JCheckBox();
        cau_hinh_mang_fn = new javax.swing.JTextField();
        tep_he_thong = new javax.swing.JCheckBox();
        tep_he_thong_fn = new javax.swing.JTextField();
        registry = new javax.swing.JCheckBox();
        registry_fn = new javax.swing.JTextField();
        lich_su_trinh_duyet = new javax.swing.JCheckBox();
        lich_su_trinh_duyet_fn = new javax.swing.JTextField();
        tep_gan_day = new javax.swing.JCheckBox();
        tep_gan_day_fn = new javax.swing.JTextField();
        eventlog = new javax.swing.JCheckBox();
        eventlog_fn = new javax.swing.JTextField();
        thong_tin_mang = new javax.swing.JCheckBox();
        thong_tin_mang_fn = new javax.swing.JTextField();
        tep_dang_mo = new javax.swing.JCheckBox();
        tep_dang_mo_fn = new javax.swing.JTextField();
        clipboard_content = new javax.swing.JCheckBox();
        clipboard_content_fn = new javax.swing.JTextField();
        thong_tin_dich_vu = new javax.swing.JCheckBox();
        thong_tin_dich_vu_fn = new javax.swing.JTextField();
        thong_tin_driver = new javax.swing.JCheckBox();
        thong_tin_driver_fn = new javax.swing.JTextField();
        process_info = new javax.swing.JCheckBox();
        process_info_fn = new javax.swing.JTextField();
        key_logger = new javax.swing.JCheckBox();
        jTextField23 = new javax.swing.JTextField();
        cmd_history = new javax.swing.JCheckBox();
        cmd_history_fn = new javax.swing.JTextField();
        cac_phien_dang_nhap = new javax.swing.JCheckBox();
        phien_dang_nhap_fn = new javax.swing.JTextField();
        list_dll = new javax.swing.JCheckBox();
        jTextField26 = new javax.swing.JTextField();
        do_phan_giai_dh = new javax.swing.JCheckBox();
        phan_giai_dh = new javax.swing.JTextField();
        handle_process = new javax.swing.JCheckBox();
        ma_nhan_dang_bao_mat = new javax.swing.JCheckBox();
        ma_nhan_dang_fn = new javax.swing.JTextField();
        trinh_dieu_khien_tep = new javax.swing.JCheckBox();
        jTextField29 = new javax.swing.JTextField();
        handle_process_fn = new javax.swing.JTextField();
        chon_ca_cot1 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        chon_ca_cot2 = new javax.swing.JCheckBox();
        chon_ca_cot3 = new javax.swing.JCheckBox();
        swapfile = new javax.swing.JCheckBox();
        jTextField31 = new javax.swing.JTextField();
        ram_img = new javax.swing.JCheckBox();
        jTextField32 = new javax.swing.JTextField();
        disk_img = new javax.swing.JCheckBox();
        jTextField33 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        chon_tat_ca = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        dump_cache = new javax.swing.JCheckBox();
        dump_cache_fn = new javax.swing.JTextField();
        thong_bao_chua_chon_thu_muc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm thu thập chứng cứ và thông tin máy tính");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Chọn một thư mục trong USB để chứa thông tin thu thập");

        jButton1.setText("Chọn thư mục");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Dữ liệu volatile");

        trang_thai_mang.setText("Trạng thái mạng");
        trang_thai_mang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trang_thai_mangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Dữ liệu non-volatile");

        cau_hinh_may_tinh.setText("Cấu hình máy tính");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Dữ liệu khác");

        ngay_gio.setText("Ngày giờ hệ thống");

        cong_duoc_mo.setText("Các cổng được mở");

        ket_noi_duoc_thiet_lap.setText("Các kết nối đã được thiết lập ");

        cong_duoc_mo_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cong_duoc_mo_fnActionPerformed(evt);
            }
        });

        bang_dinh_tuyen.setText("Bảng định tuyến");

        du_lieu_qua_cong.setText("Dữ liệu trao đổi qua cổng");

        cac_tien_trinh.setText("Các tiến trình đang hoạt động");

        nguoi_dung_dang_nhap.setText("Thông tin người dùng đăng nhập");

        cau_hinh_mang.setText("Cấu hình mạng");

        tep_he_thong.setText("Các tệp hệ thống");

        registry.setText("Dữ liệu Registry");

        lich_su_trinh_duyet.setText("Lịch sử trình duyệt ");

        tep_gan_day.setText("Các tệp sử dụng gần đây");

        eventlog.setText("Event log");

        thong_tin_mang.setText("Thông tin mạng");

        tep_dang_mo.setText("Các tệp đang mở");

        tep_dang_mo_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tep_dang_mo_fnActionPerformed(evt);
            }
        });

        clipboard_content.setText("Clipboard content");

        clipboard_content_fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clipboard_content_fnActionPerformed(evt);
            }
        });

        thong_tin_dich_vu.setText("Thông tin các dịch vụ");

        thong_tin_driver.setText("Thông tin driver");

        process_info.setText("Process information");

        key_logger.setText("Key Logger");

        cmd_history.setText("Command history");

        cac_phien_dang_nhap.setText("Các phiên đăng nhập đang hoạt động");

        list_dll.setText("List DLL");

        do_phan_giai_dh.setText("Độ phân giải của đồng hồ");

        handle_process.setText("Handle process");

        ma_nhan_dang_bao_mat.setText("Mã nhận dạng bảo mật");

        trinh_dieu_khien_tep.setText("Trình điều khiển hệ thống tệp");

        chon_ca_cot1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chon_ca_cot1.setText("Chọn tất cả ở cột này");
        chon_ca_cot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chon_ca_cot1ActionPerformed(evt);
            }
        });

        jButton6.setText("Thoát");

        jButton7.setText("Quay lại");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        chon_ca_cot2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chon_ca_cot2.setText("Chọn tất cả ở cột này");
        chon_ca_cot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chon_ca_cot2ActionPerformed(evt);
            }
        });

        chon_ca_cot3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chon_ca_cot3.setText("Chọn tất cả ở cột này");
        chon_ca_cot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chon_ca_cot3ActionPerformed(evt);
            }
        });

        swapfile.setText("Swap file");

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });

        ram_img.setText("RAM image");

        disk_img.setText("Disk image");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        chon_tat_ca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chon_tat_ca.setText("CHỌN TẤT CẢ CÁC THÔNG TIN");
        chon_tat_ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chon_tat_caActionPerformed(evt);
            }
        });

        jButton2.setText("BẮT ĐẦU THU THẬP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("TẠM DỪNG");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("KẾT THÚC THU THẬP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("LƯU TRẠNG THÁI THU THẬP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chon_tat_ca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(chon_tat_ca)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        dump_cache.setText("Dump informaktion on caches");

        thong_bao_chua_chon_thu_muc.setForeground(new java.awt.Color(255, 0, 0));
        thong_bao_chua_chon_thu_muc.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chon_ca_cot1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trang_thai_mang)
                                    .addComponent(cong_duoc_mo)
                                    .addComponent(ket_noi_duoc_thiet_lap)
                                    .addComponent(bang_dinh_tuyen)
                                    .addComponent(du_lieu_qua_cong)
                                    .addComponent(cac_tien_trinh)
                                    .addComponent(nguoi_dung_dang_nhap)
                                    .addComponent(cau_hinh_mang)
                                    .addComponent(thong_tin_mang)
                                    .addComponent(clipboard_content)
                                    .addComponent(process_info)
                                    .addComponent(cac_phien_dang_nhap)
                                    .addComponent(handle_process)
                                    .addComponent(swapfile)
                                    .addComponent(ram_img))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(trang_thai_mang_fn)
                                    .addComponent(cong_duoc_mo_fn)
                                    .addComponent(ket_noi_thiet_lap)
                                    .addComponent(bang_dinh_tuyen_fn)
                                    .addComponent(du_lieu_qua_cong_fn)
                                    .addComponent(tien_trinh)
                                    .addComponent(nguoi_dung_dang_nhap_fn)
                                    .addComponent(cau_hinh_mang_fn)
                                    .addComponent(thong_tin_mang_fn)
                                    .addComponent(clipboard_content_fn)
                                    .addComponent(process_info_fn)
                                    .addComponent(phien_dang_nhap_fn)
                                    .addComponent(handle_process_fn)
                                    .addComponent(jTextField31)
                                    .addComponent(jTextField32, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thong_bao_chua_chon_thu_muc)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(path)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 188, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cau_hinh_may_tinh)
                                    .addComponent(tep_he_thong)
                                    .addComponent(registry)
                                    .addComponent(lich_su_trinh_duyet)
                                    .addComponent(tep_gan_day)
                                    .addComponent(eventlog)
                                    .addComponent(tep_dang_mo)
                                    .addComponent(thong_tin_dich_vu)
                                    .addComponent(thong_tin_driver)
                                    .addComponent(list_dll)
                                    .addComponent(jLabel3)
                                    .addComponent(trinh_dieu_khien_tep)
                                    .addComponent(disk_img)
                                    .addComponent(chon_ca_cot2)
                                    .addComponent(dump_cache))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField33, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(cau_hinh_may_tinh_fn, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(tep_he_thong_fn)
                                    .addComponent(registry_fn)
                                    .addComponent(lich_su_trinh_duyet_fn)
                                    .addComponent(tep_gan_day_fn)
                                    .addComponent(eventlog_fn)
                                    .addComponent(tep_dang_mo_fn)
                                    .addComponent(thong_tin_dich_vu_fn)
                                    .addComponent(thong_tin_driver_fn)
                                    .addComponent(jTextField26)
                                    .addComponent(jTextField29)
                                    .addComponent(dump_cache_fn))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ngay_gio)
                                                    .addComponent(key_logger)
                                                    .addComponent(cmd_history)
                                                    .addComponent(do_phan_giai_dh)
                                                    .addComponent(ma_nhan_dang_bao_mat))
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(phan_giai_dh, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmd_history_fn, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField23, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ngay_gio_fn, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ma_nhan_dang_fn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel4)
                                            .addComponent(chon_ca_cot3))
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thong_bao_chua_chon_thu_muc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trang_thai_mang)
                            .addComponent(ngay_gio)
                            .addComponent(ngay_gio_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trang_thai_mang_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cong_duoc_mo)
                            .addComponent(cong_duoc_mo_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key_logger)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ket_noi_duoc_thiet_lap)
                            .addComponent(ket_noi_thiet_lap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_history)
                            .addComponent(cmd_history_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bang_dinh_tuyen)
                            .addComponent(bang_dinh_tuyen_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(do_phan_giai_dh)
                            .addComponent(phan_giai_dh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(du_lieu_qua_cong)
                            .addComponent(du_lieu_qua_cong_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma_nhan_dang_bao_mat)
                            .addComponent(ma_nhan_dang_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tien_trinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cac_tien_trinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nguoi_dung_dang_nhap)
                            .addComponent(nguoi_dung_dang_nhap_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cau_hinh_mang)
                            .addComponent(cau_hinh_mang_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thong_tin_mang)
                            .addComponent(thong_tin_mang_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clipboard_content)
                                    .addComponent(clipboard_content_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(process_info)
                                    .addComponent(process_info_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cau_hinh_may_tinh)
                            .addComponent(cau_hinh_may_tinh_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tep_he_thong)
                            .addComponent(tep_he_thong_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registry)
                            .addComponent(registry_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lich_su_trinh_duyet)
                            .addComponent(lich_su_trinh_duyet_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tep_gan_day)
                            .addComponent(tep_gan_day_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventlog)
                            .addComponent(eventlog_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chon_ca_cot3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tep_dang_mo)
                            .addComponent(tep_dang_mo_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thong_tin_dich_vu)
                            .addComponent(thong_tin_dich_vu_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thong_tin_driver)
                            .addComponent(thong_tin_driver_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(list_dll)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trinh_dieu_khien_tep)
                            .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cac_phien_dang_nhap)
                            .addComponent(phien_dang_nhap_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disk_img)
                            .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(handle_process)
                                .addComponent(handle_process_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dump_cache)
                                .addComponent(dump_cache_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(swapfile)
                                .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chon_ca_cot2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ram_img)
                            .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chon_ca_cot1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cong_duoc_mo_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cong_duoc_mo_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cong_duoc_mo_fnActionPerformed

    private void clipboard_content_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clipboard_content_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clipboard_content_fnActionPerformed

    private void tep_dang_mo_fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tep_dang_mo_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tep_dang_mo_fnActionPerformed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (path.getText().toString().equals("")) {
            thong_bao_chua_chon_thu_muc.setText("Bạn chưa chọn thư mục để chứa thông tin thu thập!");

        } else {
            thong_bao_chua_chon_thu_muc.setText(" ");

            if (trang_thai_mang.isSelected()) {
                try {
                    function.Function.networkStatus();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (cong_duoc_mo.isSelected()) {
                function.Function.openingPort();
            }
            if(ket_noi_duoc_thiet_lap.isSelected()){
                function.Function.establishedConnection();
            }
            if(bang_dinh_tuyen.isSelected()){
                function.Function.routerTable();
                
            }
            if(du_lieu_qua_cong.isSelected()){
                function.Function.dataPort();
                
            }
            if(cac_tien_trinh.isSelected()){
                function.Function.processList();
            }
            if(nguoi_dung_dang_nhap.isSelected()){
                function.Function.userLogIn();
            }
            if(cau_hinh_mang.isSelected()){
                function.Function.networkConfiguration();
            }
            if(thong_tin_mang.isSelected()){
                function.Function.networkInformation();
            }

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showSaveDialog(null);

        path.setText("" + f.getSelectedFile());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void chon_ca_cot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chon_ca_cot1ActionPerformed
        // TODO add your handling code here:
        if (chon_ca_cot1.isSelected()) {
            trang_thai_mang.setSelected(true);
            cong_duoc_mo.setSelected(true);
            ket_noi_duoc_thiet_lap.setSelected(true);
            bang_dinh_tuyen.setSelected(true);
            du_lieu_qua_cong.setSelected(true);
            cac_tien_trinh.setSelected(true);
            nguoi_dung_dang_nhap.setSelected(true);
            cau_hinh_mang.setSelected(true);
            thong_tin_mang.setSelected(true);
            clipboard_content.setSelected(true);
            process_info.setSelected(true);
            cac_phien_dang_nhap.setSelected(true);
            handle_process.setSelected(true);
            swapfile.setSelected(true);
            ram_img.setSelected(true);

            chon_ca_cot1.setText("Bỏ chọn tất cả cột này");

        } else {
            trang_thai_mang.setSelected(false);
            cong_duoc_mo.setSelected(false);
            ket_noi_duoc_thiet_lap.setSelected(false);
            bang_dinh_tuyen.setSelected(false);
            du_lieu_qua_cong.setSelected(false);
            cac_tien_trinh.setSelected(false);
            nguoi_dung_dang_nhap.setSelected(false);
            cau_hinh_mang.setSelected(false);
            thong_tin_mang.setSelected(false);
            clipboard_content.setSelected(false);
            process_info.setSelected(false);
            cac_phien_dang_nhap.setSelected(false);
            handle_process.setSelected(false);
            swapfile.setSelected(false);
            ram_img.setSelected(false);
            chon_ca_cot1.setText("Chọn tất cả cột này");

        }


    }//GEN-LAST:event_chon_ca_cot1ActionPerformed

    private void chon_ca_cot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chon_ca_cot2ActionPerformed
        // TODO add your handling code here:
        if (chon_ca_cot2.isSelected()) {
            cau_hinh_may_tinh.setSelected(true);
            tep_he_thong.setSelected(true);
            registry.setSelected(true);
            lich_su_trinh_duyet.setSelected(true);
            tep_gan_day.setSelected(true);
            eventlog.setSelected(true);
            tep_dang_mo.setSelected(true);
            thong_tin_dich_vu.setSelected(true);
            thong_tin_driver.setSelected(true);
            list_dll.setSelected(true);
            trinh_dieu_khien_tep.setSelected(true);
            disk_img.setSelected(true);
            dump_cache.setSelected(true);
            chon_ca_cot2.setText("Bỏ chọn tất cả cột này");

        } else {
            cau_hinh_may_tinh.setSelected(false);
            tep_he_thong.setSelected(false);
            registry.setSelected(false);
            lich_su_trinh_duyet.setSelected(false);
            tep_gan_day.setSelected(false);
            eventlog.setSelected(false);
            tep_dang_mo.setSelected(false);
            thong_tin_dich_vu.setSelected(false);
            thong_tin_driver.setSelected(false);
            list_dll.setSelected(false);
            trinh_dieu_khien_tep.setSelected(false);
            disk_img.setSelected(false);
            dump_cache.setSelected(false);
            chon_ca_cot2.setText("Chọn tất cả cột này");

        }
    }//GEN-LAST:event_chon_ca_cot2ActionPerformed

    private void chon_ca_cot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chon_ca_cot3ActionPerformed
        // TODO add your handling code here:
        if (chon_ca_cot3.isSelected()) {
            ngay_gio.setSelected(true);
            key_logger.setSelected(true);
            cmd_history.setSelected(true);
            do_phan_giai_dh.setSelected(true);
            ma_nhan_dang_bao_mat.setSelected(true);
            chon_ca_cot3.setText("Bỏ chọn tất cả cột này");

        } else {
            ngay_gio.setSelected(false);
            key_logger.setSelected(false);
            cmd_history.setSelected(false);
            do_phan_giai_dh.setSelected(false);
            ma_nhan_dang_bao_mat.setSelected(false);
            chon_ca_cot3.setText("Chọn tất cả cột này");
        }
    }//GEN-LAST:event_chon_ca_cot3ActionPerformed

    private void chon_tat_caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chon_tat_caActionPerformed
        // TODO add your handling code here:
        if (chon_tat_ca.isSelected()) {
            chon_tat_ca.setText("BỎ CHỌN TẤT CẢ");
            chon_ca_cot1.setSelected(true);
            chon_ca_cot2.setSelected(true);
            chon_ca_cot3.setSelected(true);
            //cot1
            trang_thai_mang.setSelected(true);
            cong_duoc_mo.setSelected(true);
            ket_noi_duoc_thiet_lap.setSelected(true);
            bang_dinh_tuyen.setSelected(true);
            du_lieu_qua_cong.setSelected(true);
            cac_tien_trinh.setSelected(true);
            nguoi_dung_dang_nhap.setSelected(true);
            cau_hinh_mang.setSelected(true);
            thong_tin_mang.setSelected(true);
            clipboard_content.setSelected(true);
            process_info.setSelected(true);
            cac_phien_dang_nhap.setSelected(true);
            handle_process.setSelected(true);
            swapfile.setSelected(true);
            ram_img.setSelected(true);
            chon_ca_cot1.setText("Bỏ chọn tất cả cột này");
            //cot2
            cau_hinh_may_tinh.setSelected(true);
            tep_he_thong.setSelected(true);
            registry.setSelected(true);
            lich_su_trinh_duyet.setSelected(true);
            tep_gan_day.setSelected(true);
            eventlog.setSelected(true);
            tep_dang_mo.setSelected(true);
            thong_tin_dich_vu.setSelected(true);
            thong_tin_driver.setSelected(true);
            list_dll.setSelected(true);
            trinh_dieu_khien_tep.setSelected(true);
            disk_img.setSelected(true);
            dump_cache.setSelected(true);
            chon_ca_cot2.setText("Bỏ chọn tất cả cột này");
            //cot3
            ngay_gio.setSelected(true);
            key_logger.setSelected(true);
            cmd_history.setSelected(true);
            do_phan_giai_dh.setSelected(true);
            ma_nhan_dang_bao_mat.setSelected(true);
            chon_ca_cot3.setText("Bỏ chọn tất cả cột này");

        } else {
            chon_tat_ca.setText("CHỌN TẤT CẢ THÔNG TIN");
            chon_ca_cot1.setSelected(false);
            chon_ca_cot2.setSelected(false);
            chon_ca_cot3.setSelected(false);
            //COT1
            trang_thai_mang.setSelected(false);
            cong_duoc_mo.setSelected(false);
            ket_noi_duoc_thiet_lap.setSelected(false);
            bang_dinh_tuyen.setSelected(false);
            du_lieu_qua_cong.setSelected(false);
            cac_tien_trinh.setSelected(false);
            nguoi_dung_dang_nhap.setSelected(false);
            cau_hinh_mang.setSelected(false);
            thong_tin_mang.setSelected(false);
            clipboard_content.setSelected(false);
            process_info.setSelected(false);
            cac_phien_dang_nhap.setSelected(false);
            handle_process.setSelected(false);
            swapfile.setSelected(false);
            ram_img.setSelected(false);
            chon_ca_cot1.setText("Chọn tất cả cột này");
            //COT2
            cau_hinh_may_tinh.setSelected(false);
            tep_he_thong.setSelected(false);
            registry.setSelected(false);
            lich_su_trinh_duyet.setSelected(false);
            tep_gan_day.setSelected(false);
            eventlog.setSelected(false);
            tep_dang_mo.setSelected(false);
            thong_tin_dich_vu.setSelected(false);
            thong_tin_driver.setSelected(false);
            list_dll.setSelected(false);
            trinh_dieu_khien_tep.setSelected(false);
            disk_img.setSelected(false);
            dump_cache.setSelected(false);
            chon_ca_cot2.setText("Chọn tất cả cột này");
            //COT3
            ngay_gio.setSelected(false);
            key_logger.setSelected(false);
            cmd_history.setSelected(false);
            do_phan_giai_dh.setSelected(false);
            ma_nhan_dang_bao_mat.setSelected(false);
            chon_ca_cot3.setText("Chọn tất cả cột này");

        }
    }//GEN-LAST:event_chon_tat_caActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        (new Checkin()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void trang_thai_mangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trang_thai_mangActionPerformed
        // TODO add your handling code here:
        if (trang_thai_mang.isSelected() == false) {
            chon_ca_cot1.setSelected(false);
            chon_ca_cot1.setText("Chọn tất cả cột này");
        }
    }//GEN-LAST:event_trang_thai_mangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bang_dinh_tuyen;
    public static javax.swing.JTextField bang_dinh_tuyen_fn;
    private javax.swing.JCheckBox cac_phien_dang_nhap;
    private javax.swing.JCheckBox cac_tien_trinh;
    private javax.swing.JCheckBox cau_hinh_mang;
    public static javax.swing.JTextField cau_hinh_mang_fn;
    private javax.swing.JCheckBox cau_hinh_may_tinh;
    public static javax.swing.JTextField cau_hinh_may_tinh_fn;
    private javax.swing.JCheckBox chon_ca_cot1;
    private javax.swing.JCheckBox chon_ca_cot2;
    private javax.swing.JCheckBox chon_ca_cot3;
    private javax.swing.JCheckBox chon_tat_ca;
    private javax.swing.JCheckBox clipboard_content;
    public static javax.swing.JTextField clipboard_content_fn;
    private javax.swing.JCheckBox cmd_history;
    public static javax.swing.JTextField cmd_history_fn;
    private javax.swing.JCheckBox cong_duoc_mo;
    public static javax.swing.JTextField cong_duoc_mo_fn;
    private javax.swing.JCheckBox disk_img;
    private javax.swing.JCheckBox do_phan_giai_dh;
    private javax.swing.JCheckBox du_lieu_qua_cong;
    public static javax.swing.JTextField du_lieu_qua_cong_fn;
    private javax.swing.JCheckBox dump_cache;
    public static javax.swing.JTextField dump_cache_fn;
    private javax.swing.JCheckBox eventlog;
    public static javax.swing.JTextField eventlog_fn;
    private javax.swing.JCheckBox handle_process;
    public static javax.swing.JTextField handle_process_fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JCheckBox ket_noi_duoc_thiet_lap;
    public static javax.swing.JTextField ket_noi_thiet_lap;
    private javax.swing.JCheckBox key_logger;
    private javax.swing.JCheckBox lich_su_trinh_duyet;
    public static javax.swing.JTextField lich_su_trinh_duyet_fn;
    private javax.swing.JCheckBox list_dll;
    private javax.swing.JCheckBox ma_nhan_dang_bao_mat;
    public static javax.swing.JTextField ma_nhan_dang_fn;
    private javax.swing.JCheckBox ngay_gio;
    public static javax.swing.JTextField ngay_gio_fn;
    private javax.swing.JCheckBox nguoi_dung_dang_nhap;
    public static javax.swing.JTextField nguoi_dung_dang_nhap_fn;
    public static javax.swing.JTextField path;
    public static javax.swing.JTextField phan_giai_dh;
    public static javax.swing.JTextField phien_dang_nhap_fn;
    private javax.swing.JCheckBox process_info;
    public static javax.swing.JTextField process_info_fn;
    private javax.swing.JCheckBox ram_img;
    private javax.swing.JCheckBox registry;
    public static javax.swing.JTextField registry_fn;
    private javax.swing.JCheckBox swapfile;
    private javax.swing.JCheckBox tep_dang_mo;
    public static javax.swing.JTextField tep_dang_mo_fn;
    private javax.swing.JCheckBox tep_gan_day;
    public static javax.swing.JTextField tep_gan_day_fn;
    private javax.swing.JCheckBox tep_he_thong;
    public static javax.swing.JTextField tep_he_thong_fn;
    private javax.swing.JLabel thong_bao_chua_chon_thu_muc;
    private javax.swing.JCheckBox thong_tin_dich_vu;
    public static javax.swing.JTextField thong_tin_dich_vu_fn;
    private javax.swing.JCheckBox thong_tin_driver;
    public static javax.swing.JTextField thong_tin_driver_fn;
    private javax.swing.JCheckBox thong_tin_mang;
    public static javax.swing.JTextField thong_tin_mang_fn;
    public static javax.swing.JTextField tien_trinh;
    private javax.swing.JCheckBox trang_thai_mang;
    public static javax.swing.JTextField trang_thai_mang_fn;
    private javax.swing.JCheckBox trinh_dieu_khien_tep;
    // End of variables declaration//GEN-END:variables
}
